### ISSUE TITLE
Plots and data file need work before we can proceed

### ISSUE THREAD

**Issue by quantifish** [quantifish/isotope#14]
I have added comments to the Plot.R file, this is now practically unreadable and will break the minute anything changes in the model making model exploration very difficult, I suggest changing back to what we had before and expand on that. All the priors work when using that code, I have added in some examples.

Why does the species column have a number in front? You should remove this from the data file, it is simply taxa and species combined which should be done in the code, it makes the plots hard to make look nice when a number is sitting next to the name. You can make the points look different to differentiate between taxa, I added an example.

You have plots names mcmc_par... that contain variables that are not parameters (e.g. C_tot and N_tot). This is confusing and needs to be changed, you don't even need to plot trace plots of these posteriors as these are MCMC diagnostic plots and all we care about is parameters when looking at diagnostics.

Essentially what we want to be able to do is change anything we want in the model, then run the Plot.R file without needing to change anything in the file, and look at the plots. We can then repeat this over and over doing things like dropping out species, or changing the number of parameters, etc etc. This is what the old code did.

**Comment by quantifish** [comment]
Just to add a positive comment, the results are starting to look really good, especially when looking at the fit plots. The hydrogen component really looks like it is adding value to the analysis.

**Comment by yarimitsu** [comment]
Thanks for looking at this so quickly Darcy. I'll  work on the plots first
thing Monday morning (tomorrow). I am SFL to have your awesome help...

**Comment by yarimitsu** [comment]
[x] use grepl instead of messed up index
[x] get rid of ggsave (ie worst POS ever written! haha)
[x] got rid of transformed parameter plots - check

[x] took numbers out of species...never mess w data
[x] don't use RStudio comment shortcut because it inserts tabs

Still an issue that I can't figure out - some prior lines are plotting correctly (e.g., dCs), but not the following:
 sigma_phi.3s
 dN.1
 dN.3
 Delta_H
 Delta_N

**Comment by quantifish** [comment]
All the priors are plotting correctly now, the sigma_phis are uniform and the other pars you listed are simply just showing the tail of the prior

**Comment by quantifish** [comment]
OK now the problem is that we seem to be getting bimodal distributions! This is happening in most of the source estimates, some of the sigma_frc, some of the phi's. The histograms show the quite clearly. Try to have a think about why that may be and do some extra runs to investigate??? You may know better than I what to do next. I can take another look tomo.

**Comment by yarimitsu** [comment]
OK I'll explore that a bit.

**Comment by yarimitsu** [comment]
There are several factors that could be causing a bimodal distribution, I made some plots of CNH ~ year, fjord, fish length by species. Adding a fjord grouping variable might help (but not all species were sampled in every fjord). 

I also messsed with including separate Delta_H parameters for marine vs freshwater, or separate Delta_N parameters for each species. Neither took care of the problem by itself. However, there is a real possibility that Delta_N differs among taxa (especially zooplankton compared to the other taxa). 

There is a paper that shows 2H is related to fish size, and of course it's well known that larger fish may feed at a higher trophic level (so positive relationship between 15N and size...although it's definitely not a smoking gun.

Possible ways to go are 1) fjord as a second grouping variable for phis, 2) separate delta_N for each taxa. I get stuck when trying add another grouping variable to the equations for dC_exp, dH_exp, and dN_exp. 

One last thought: do you think going with individual estimates rather than grouped dX-exp's would help? That would allow individual tau and dH_w to come into play, but really don't know if it matters... I'm getting buggy eyed and need to put this down for a few hours. Let me know what you think is a reasonable way forward. THANKS...

**Comment by quantifish** [comment]
These plots are starting to look great Yumi, great work! Plus, the plotting code all works without needing to do anything - fantastic! Although I did just bugger it up for you (I was aiming to get the source, marine, coastal, fresh into our fit plots) and will leave this for you to finish off for me, I am obviously doing something wrong.

OK, so I added some plots as well, and I didn't really see a huge impact of Fjord or size. I don't think we want to go to the individual level (at least not yet) as we run the risk of over-parameterising the model.

Because everything looked reasonable I suspected that it may be an MCMC issue... and it was. We were saving way to many samples from the posterior (5000) so our plots always looked good despite the model mixing poorly. Poor mixing is fixed with longer MCMC runs so take a look now. I think we need to run this model for even longer again, but for now this will do. I think you should have another play and become familiar with it all again, then we could talk on google tomo if you like?

**Comment by yarimitsu** [comment]
Awesome Darcy! Way to sleuth it. God I'm so pathetic (chasing rabbits all day!)...but I'm glad it was just the MCMC, which so much easier to deal with than adding more complexity to the model. I am super excited about the way things are shaping up. 

Adding the source parameters to the plots is a good idea. This typically makes the most sense when we adjust the source estimates by the fractionation estimates N_tot, C_tot and Delta_H. Delta H doesn't change by species, but dH_obs needs to be adjusted for omega to look right on the plot.  Fortunately you have taught me enough to know how to make all this happen with transformed parameters, and that's what I'm going to work on today. This plot is going to be RAD and hopefully will take me less than 12 hours to make :). Timer starts now.
