### ISSUE TITLE
What is the current model doing?

### ISSUE THREAD

**Issue by quantifish** [quantifish/isotope#9]
To move forward we need to know what the current model is doing.

At the moment it looks like we are fitting to two species as if they were one... Is that right?

And where we want to get to is fitting to all species, each with their own estimated parameters, and some shared parameters... Is that right?

Do you have a document that you have written somewhere describing the math and the model (in your own words)?

I'm sorry Yumi but it is taking me a while to figure all this stuff out. We need waaaayyyyy more figures.

**Comment by quantifish** [comment]
OK, I got the figures sorted so ow I can get a good feeling for what's happening. Sorry to code away over top of your hard work Yumi.

**Comment by quantifish** [comment]
OK more questions, about future structure now. Below is our models parameter section:

    parameters {
      real dC[3]; // 13C marine, coastal and freshwater source endmember
      real dH[3];
      simplex[3] phi; // phi is defined as a unit simplex and thus sum(phi)=1
      real<lower=0> sigma[8];
      real<lower=0, upper=1> omega;
      real Delta_C;
      real dH_p;
    }

The next step (correct me if I am wrong) is to extend our model for 2 species (then more). To do this we need to figure out which parameters are species-specific, and which parameters are constant across species. Now I dont know what an endmember is (sounds like the end of a penis) but it seems like our `dC` and `dH` parameters should be shared across all species, the `phi` pars should be species-specific, the `omega`, `Delta_C`, and `dH_p` shared, and the `sigma`'s will be a mixed bag I guess (e.g. `sigma_dC` might be shared). Does this sound about right? I will not do any more until you give the word, but you might wanna let me think about how to code this extension up as things could get messy very quickly here.

**Comment by yarimitsu** [comment]
haha. I thought you would get a kick out of the term endmember.... NUTS is
no-u-turn sampler that is the default sampling algorithm not MCMC...so it
seemed weird to not change it. Plus endmembers and NUTS go together like
peas and carrots.

YEs, the main objective is to estimate phis for each species. Originally it
seemed like grouping functional groups (like krill, fish, birds) would be
OK but it seems that different species are incorporating hydrogen and
carbon in different ways different proportions.

I think you're correct in your description of shared vs species-specific
parameters above. dC, dH, dH_p, omega are all shared. Sigma_dC[1:3],
sigma_dH[1:3], sigma_omega, sigma_dH_p should be shared.

Delta_C is tricky. There is variability across species and systems, carbon
is generally thought to be "conservative" but is known to change between
0-1 per mil per trophic level. SO euphausiids at higher tau (i.e., feeding
on a diet of zooplankton rather than phytoplankton, and thus having higher
15N ratios) may have higher carbon values by up to 1 per mil compared to
their food. HOWEVER, I think for simplicity's sake it makes sense to treat
all euphausiids from the same kind of environment similarly, and that means
sharing delta_C. I can run each trophic level separately so that there is
only a single hierarchical level to deal with. That means sigma_delta_C is
shared too.

phi[1:3] will change for each species.

Sorry for any confusion. I will work on a better explanation of the model
now.

**Comment by quantifish** [comment]
OK, sounds good. Gotta to for now. I have just pushed. Made a lot of changes to plots and have restructured some code in anticipation of the future changes. I am happy with the plots for now as we can see all posteriors, priors and model fits. I will work on coding up for multiple species tonight and see what we make of it. It will be tricky to create plots that capture everything by species etc, but we will get there.

**Comment by yarimitsu** [comment]
OR maybe I should just do one species at a time and we call it pretty good.

The main reason I wanted to do the hierarchical thing was because the
LaPlaces Demon model had parameters all over the place and I just didn't
know enough to realize how messed up it was. This stan implementation is
working so much better. Now that I have some confidence in the model, I'm
glad to skip the hassle and heartache of adding more complexity, and it
would be easy to do each species separately from here.

Those plots - so much better. Anything that looks like a bullseye should be
worked in wherever possible in my opinion...

THANKS for all your time on this. Sorry it's such a can of worms and I have
almost nothing to contribute. I owe you so big for this.

**Comment by quantifish** [comment]
Nah so the multi-species approach has a lot of merit because those parameters that are shared will be estimated really well and then that means the other pars for each species come out better too! Plus it makes your work better than the other guys
On 18 Aug 2015 17:12, yarimitsu <notifications@github.com> wrote:OR maybe I should just do one species at a time and we call it pretty good.

The main reason I wanted to do the hierarchical thing was because the
LaPlaces Demon model had parameters all over the place and I just didn't
know enough to realize how messed up it was. This stan implementation is
working so much better. Now that I have some confidence in the model, I'm
glad to skip the hassle and heartache of adding more complexity, and it
would be easy to do each species separately from here.

Those plots - so much better. Anything that looks like a bullseye should be
worked in wherever possible in my opinion...

THANKS for all your time on this. Sorry it's such a can of worms and I have
almost nothing to contribute. I owe you so big for this.

**Comment by quantifish** [comment]
OK, so take a look now. I have extended the model for multiple species. I reckon we should proceed cautiously by adding another 4 species (keep the current 2) and repeating. Then we need to start deciding on the parameter/model structure carefully again. So over to you. I would recommend choosing some species that are quite different from the current 2 and different to each other. Chuck em in that data file, then have a play and let me know and I can take another look.

**Comment by yarimitsu** [comment]
Thanks for working on this. Today I've been working on a write-up of the
model to help clarify things. I'll send it as soon as it's ready.

I'm psyched to dig into this new thing you've set up. There is an issue:
there are only 2 species of euphausiids, so if I chuck some more data in
there they will be from a different trophic level...and then things need to
accommodate fractionation across trophic levels (will need to implement
C_tot and omega_tot, which point to tau). I do have 5 species of fish so
I'm going to try to mess with those first. I'll be in touch as soon as I
get it sorted out.

**Comment by quantifish** [comment]
OK cool, lets try the 5 species of fish instead. Also, lets get dN back in there, it will help tighten up estimates of phi (more data always better)
